package com.vyxentra.vehicle.enums;


public enum BookingStatus {
    PENDING_PAYMENT,
    PENDING_CONFIRMATION,
    CONFIRMED,
    ASSIGNED,
    IN_PROGRESS,
    COMPLETED,
    CANCELLED,
    EXPIRED,
    DAMAGE_REPORTED,
    DAMAGE_APPROVED,
    DAMAGE_REJECTED,
    WAITING_FOR_APPROVAL,
    CAN_BECANCELLED;
}