package com.vyxentra.vehicle.enums;

public enum DamageStatus {
    REPORTED,
    AWAITING_APPROVAL,
    APPROVED,
    PARTIALLY_APPROVED,
    REJECTED,
    IN_REPAIR,
    REPAIRED,
    PENDING_ASSIGNMENT,
    ASSIGNED,
    PAYMENT_PENDING,
    REPAIR_IN_PROGRESS,
    DAMAGE_REPORTED,
    DAMAGE_APPROVED,
    WASH_IN_PROGRESS,
    WASH_COMPLETED,
    COMPLETED,
    CANCELLED,
    EXPIRED


}
